<a href="https://colab.research.google.com/github/palpitation0/Machine-Learning-homework/blob/master/13%EA%B0%95_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

In [0]:
iris = load_iris()

In [6]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
sy = pd.Series(iris.target, dtype="category")
sy = sy.cat.rename_categories(iris.target_names)
df['species'] = sy
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species
0                5.1               3.5  ...               0.2   setosa
1                4.9               3.0  ...               0.2   setosa
2                4.7               3.2  ...               0.2   setosa
3                4.6               3.1  ...               0.2   setosa
4                5.0               3.6  ...               0.2   setosa

[5 rows x 5 columns]

In [0]:
from sklearn.model_selection import train_test_split
x = df.iloc[:, 0:2] # 꽃받침의 폭과 길이만 이용
y = df.iloc[:, 4]
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [16]:
from sklearn.svm import SVC
iris_model = SVC()
iris_model.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, iris_pred))

[[16  1  0]
 [ 0 12  4]
 [ 0  3  9]]


In [21]:
print(classification_report(y_test, iris_pred))

              precision    recall  f1-score   support

      setosa       1.00      0.94      0.97        17
  versicolor       0.75      0.75      0.75        16
   virginica       0.69      0.75      0.72        12

    accuracy                           0.82        45
   macro avg       0.81      0.81      0.81        45
weighted avg       0.83      0.82      0.82        45



In [0]:
x = df.iloc[:, :-1] # 꽃잎의 폭과 길이까지 이용
y = df.iloc[:, 4]
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [23]:
iris_model_2 = SVC()
iris_model_2.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
iris_pred = iris_model_2.predict(x_test)

In [25]:
print(confusion_matrix(y_test, iris_pred))

[[20  0  0]
 [ 0 13  0]
 [ 0  3  9]]


In [26]:
print(classification_report(y_test, iris_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        20
  versicolor       0.81      1.00      0.90        13
   virginica       1.00      0.75      0.86        12

    accuracy                           0.93        45
   macro avg       0.94      0.92      0.92        45
weighted avg       0.95      0.93      0.93        45



In [0]:
# 꽃받침만 이용한 SVM 에 비해 꽃잎까지 이용한 경우 정확도가 0.83 에서 0.95 로 개선됨